version: '2'
services:
    jhipsimple-app:
        image: jhipsimple
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsimple-postgresql:5432/jhipsimple
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsimple-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsimple-postgresql
